package views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Panel;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ConnectionDesign extends Panel {
	protected ComboBox<java.lang.String> comboPort;
	protected ComboBox<java.lang.String> comboSpeed;
	protected Button buttonConnect;
	protected Button buttonRefresh;

	public ConnectionDesign() {
		Design.read(this);
	}
}
