package views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class GReaderDesign extends Panel {
	protected VerticalLayout greaderLayout;
	protected TextField pathFileField;
	protected TextField exeCountField;
	protected HorizontalLayout buttonBar;
	protected Button buttonStart;
	protected Button buttonOneStep;
	protected Button buttonReaload;
	protected Button buttonPause;

	public GReaderDesign() {
		Design.read(this);
	}
}
