package views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.RadioButtonGroup;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class NavigationPanelDesign extends VerticalLayout {
	protected HorizontalLayout top;
	protected VerticalLayout positionLayout;
	protected Panel position;
	protected VerticalLayout barLayout;
	protected HorizontalLayout barX;
	protected TextField xPositionField;
	protected Button button0X;
	protected HorizontalLayout barY;
	protected TextField yPositionFiled;
	protected Button button0Y;
	protected HorizontalLayout barZ;
	protected TextField zPositionField;
	protected Button button0Z;
	protected VerticalLayout joggingLayout;
	protected Panel jogging;
	protected HorizontalLayout joggingGroup;
	protected HorizontalLayout ratioLayout;
	protected RadioButtonGroup<java.lang.String> ratioDistance;
	protected RadioButtonGroup<java.lang.String> ratioFeed;
	protected GridLayout jogButton;
	protected Button buttonPlusY;
	protected Button buttonPlusZ;
	protected Button buttonMinusX;
	protected Button buttonPlusX;
	protected Button buttonMinusY;
	protected Button buttonMinusZ;
	protected Panel control;
	protected HorizontalLayout controlBar;
	protected TextField stateField;
	protected Button buttonHold;
	protected Button buttonResume;
	protected Button buttonReset;
	protected Button buttonUnlock;

	public NavigationPanelDesign() {
		Design.read(this);
	}
}
